# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufable/problem.proto

require 'google/protobuf'


descriptor_data = "\n\x1aprotobufable/problem.proto\x12\x0cprotobufable\"G\n\x12ProblemTypeOptions\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1f\n\x0bhttp_status\x18\x02 \x01(\rR\nhttpStatusb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protobufable
  ProblemTypeOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.ProblemTypeOptions").msgclass
end
