# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufable/problem_details.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'


descriptor_data = "\n\"protobufable/problem_details.proto\x12\x0cprotobufable\x1a\x19google/protobuf/any.proto\"\xbe\x01\n\x0eProblemDetails\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n\x06\x64\x65tail\x18\x04 \x01(\tR\x06\x64\x65tail\x12\x1a\n\x08instance\x18\x05 \x01(\tR\x08instance\x12\x36\n\x0binformation\x18\x06 \x03(\x0b\x32\x14.google.protobuf.AnyR\x0binformationb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protobufable
  ProblemDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.ProblemDetails").msgclass
end
