# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufable/testing/v1/fixtures.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'google/protobuf/descriptor_pb'
require 'google/protobuf/timestamp_pb'
require 'google/rpc/error_details_pb'
require 'protobufable/problem_pb'


descriptor_data = "\n&protobufable/testing/v1/fixtures.proto\x12\x17protobufable.testing.v1\x1a\x1b\x62uf/validate/validate.proto\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/rpc/error_details.proto\x1a\x1aprotobufable/problem.proto\"\xa9\x01\n\x05\x44ummy\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\x12\n\x05\x63ount\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x06nested\x18\x04 \x01(\x0b\x32\x1f.protobufable.testing.v1.Nested\x12\x10\n\x08password\x18\x05 \x01(\tB\x08\n\x06_count\"\x17\n\x06Nested\x12\r\n\x05label\x18\x01 \x01(\t\"?\n\x12InformationCarrier\x12)\n\nretry_info\x18\x01 \x01(\x0b\x32\x15.google.rpc.RetryInfo\"y\n\x13\x43reateWidgetRequest\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x64\x12\x18\n\x04tags\x18\x02 \x03(\tB\n\xbaH\x07\x92\x01\x04\x10\x08\x18\x01\x12/\n\x06nested\x18\x03 \x01(\x0b\x32\x1f.protobufable.testing.v1.Nested*\x81\x02\n\x0bProblemType\x12\x1c\n\x18PROBLEM_TYPE_UNSPECIFIED\x10\x00\x12-\n\x16PROBLEM_TYPE_NOT_FOUND\x10\x01\x1a\x11\x82V\x0e\n\tnot-found\x10\x94\x03\x12-\n\x16PROBLEM_TYPE_FORBIDDEN\x10\x02\x1a\x11\x82V\x0e\n\tforbidden\x10\x93\x03\x12\x37\n PROBLEM_TYPE_FORBIDDEN_SUSPENDED\x10\x03\x1a\x11\x82V\x0e\n\tforbidden\x10\x93\x03\x12=\n\x1ePROBLEM_TYPE_TOO_MANY_REQUESTS\x10\x04\x1a\x19\x82V\x16\n\x11too-many-requests\x10\xad\x03*\xa6\x01\n\x11LegacyProblemType\x12#\n\x1fLEGACY_PROBLEM_TYPE_UNSPECIFIED\x10\x00\x12\x35\n\x1dLEGACY_PROBLEM_TYPE_NOT_FOUND\x10\x01\x1a\x12\x8a\xb5\x18\tnot-found\x90\xb5\x18\x94\x03\x12\x35\n\x1dLEGACY_PROBLEM_TYPE_FORBIDDEN\x10\x02\x1a\x12\x8a\xb5\x18\tforbidden\x90\xb5\x18\x93\x03:B\n\x12legacy_problem_uri\x12!.google.protobuf.EnumValueOptions\x18\xd1\x86\x03 \x01(\t\x88\x01\x01:B\n\x12legacy_http_status\x12!.google.protobuf.EnumValueOptions\x18\xd2\x86\x03 \x01(\r\x88\x01\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protobufable
  module Testing
    module V1
      Dummy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.testing.v1.Dummy").msgclass
      Nested = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.testing.v1.Nested").msgclass
      InformationCarrier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.testing.v1.InformationCarrier").msgclass
      CreateWidgetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.testing.v1.CreateWidgetRequest").msgclass
      ProblemType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.testing.v1.ProblemType").enummodule
      LegacyProblemType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobufable.testing.v1.LegacyProblemType").enummodule
    end
  end
end
